# official doc: https://developers.openai.com/codex/local-config#cli
# refarences:
# - https://github.com/feiskyer/codex-settings
# - https://github.com/openai/codex/issues/2760

apploval_policy = "untrusted"
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Glass.aiff"]
network_access = false
show_raw_agent_reasoning = true
experimental_use_rmcp_client = true

[tui]
notifications = ["agent-turn-complete", "approval-requested"]

[shell_environment_policy]
inherit = "core"
include_only = ["PATH", "HOME", "USER"]
exclude = ["AWS_*", "AZUER_*", "*TOKEN*", "*SECRET*", "*KEY*"]

[tools]
web_search = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
startup_timeout_sec = 20.0

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_MCP_PAT"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex", "--enable-web-dashboard=false", "--project", "$(pwd)"]
startup_timeout_sec = 20.0
