[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
  let g:quickrun_config = {
    'runner' : 'vimproc',
    'runner/vimproc/updatetime' : 60,
    'outputter/buffer/close_on_empty' : 1,
  }
'''
