"vunlde.vimで管理してるpluginを読み込む
"source ~/dotfiles/.config/vim/.vimrc.bundle

let s:vim_config_base = empty($XDG_CONFIG_PATH) ? '~/dotfiles/.config' : $XDG_CONFIG_PATH
let s:vim_config_dir = expand(s:vim_config_base . '/vim')
function! s:SourceConfig(file) abort
  execute 'source ' . fnameescape(s:vim_config_dir . '/' . a:file)
endfunction

"基本設定
call s:SourceConfig('.vimrc.basic')
"dein.vimで管理してるpluginを読み込む
call s:SourceConfig('.vimrc.dein')
"StatusLine設定
call s:SourceConfig('.vimrc.statusline')
"インデント設定
call s:SourceConfig('.vimrc.indent')
"表示関連
call s:SourceConfig('.vimrc.apperance')
"補完関連
call s:SourceConfig('.vimrc.completion')
"Tags関連
" call s:SourceConfig('.vimrc.tags')
"検索関連
call s:SourceConfig('.vimrc.search')
"移動関連
call s:SourceConfig('.vimrc.moving')
"Color関連
call s:SourceConfig('.vimrc.colors')
"編集関連
call s:SourceConfig('.vimrc.editing')
"エンコーディング関連
call s:SourceConfig('.vimrc.encoding')
"その他
" call s:SourceConfig('.vimrc.misc')
