"vunlde.vimで管理してるpluginを読み込む
"source ~/dotfiles/.config/vim/.vimrc.bundle

"基本設定
source ~/dotfiles/.config/vim/.vimrc.basic
"dein.vimで管理してるpluginを読み込む
source ~/dotfiles/.config/vim/.vimrc.dein
"StatusLine設定
source ~/dotfiles/.config/vim/.vimrc.statusline
"インデント設定
source ~/dotfiles/.config/vim/.vimrc.indent
"表示関連
source ~/dotfiles/.config/vim/.vimrc.apperance
"補完関連
source ~/dotfiles/.config/vim/.vimrc.completion
"Tags関連
" source ~/dotfiles/.config/vim/.vimrc.tags
"検索関連
source ~/dotfiles/.config/vim/.vimrc.search
"移動関連
source ~/dotfiles/.config/vim/.vimrc.moving
"Color関連
source ~/dotfiles/.config/vim/.vimrc.colors
"編集関連
source ~/dotfiles/.config/vim/.vimrc.editing
"エンコーディング関連
source ~/dotfiles/.config/vim/.vimrc.encoding
"その他
" source ~/dotfiles/.config/vim/.vimrc.misc
